ZaposleniMVC/Models/Raspored.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ZaposleniMVC.Models
{
    public class Raspored
    {
        
        [Key]
        public int RasporedID { get; set; }
        [Required]
        public DateTime Datum { get; set; }
        
        public Administrator Administrator { get; set; }
        
        public Zaposleni Zaposleni { get; set; }
        [Required]
        public string Smena { get; set; }
        public DateTime VremePrijave { get; set; }

        public bool Kasni { get; set; } = false;
        public string Obavestenje { get; set; }
    }
}

ZaposleniMVC/Controllers/KompanijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ZaposleniMVC.Models;

namespace ZaposleniMVC.Controllers
{
    public class KompanijaController : Controller
    {
        private readonly ApplicationDbContext _db;


        public KompanijaController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            Odgovor o = new Odgovor();
            if (_db.Kompanija.Count() == 0)
            {
                o.Kompanija = new Kompanija();

                return View(o);
            }

            return RedirectToAction("Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Kompanija kompanija)
        {
            Odgovor o = new Odgovor();
            o.Kompanija = new Kompanija();
            try
            {
                _db.Add(kompanija);
                _db.SaveChanges();
                return RedirectToAction("Edit");

            }
            catch (Exception)
            {

                o.Poruka = "Greska";
            }
            return View(o);
        }

        public IActionResult Edit()
        {
            Odgovor o = new Odgovor();
            o.Kompanija = _db.Kompanija.First();

            return View(o);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Kompanija kompanija)
        {
            Odgovor o = new Odgovor();
            o.Kompanija = kompanija;

            try
            {
                List<string> lista = ProveraOpste(o.Kompanija);
                if (lista.Count > 0)
                {
                    o.Validacija = lista;
                    o.Poruka = "Greska";
                    return View(o);
                }
                _db.Update(kompanija);
                _db.SaveChanges();
                o.Poruka = "Ok";

            }
            catch (Exception)
            {

                o.Poruka = "Greska";
            }
            return View(o);
        }

        private List<string> ProveraOpste(Kompanija kompanija)
        {
            List<string> lista = new List<string>();
            if (!ProveraNaziv(kompanija.Naziv)) lista.Add("naziv");
            if (!ProveraMaticni(kompanija.MaticniBroj)) lista.Add("maticni");
            if (!ProveraDelatnost(kompanija.Delatnost)) lista.Add("delatnost");
            if (!ProveraAdresa(kompanija.Adresa)) lista.Add("adresa");


            return lista;

        }

        private bool ProveraNaziv(string naziv)
        {
            if (naziv is null || naziv.Length <= 2) return false;
            return true;
        }
        private bool ProveraAdresa(string adresa)
        {
            if (adresa is null) return false;
            string[] niz = adresa.Split(' ');
            int brojReci = 0;
            int brojUlice = 0;
            foreach (string s in niz)
            {
                if (Regex.IsMatch(s, @"^[a-zA-Z]+$")) brojReci++;
                if (Regex.IsMatch(s, @"^[0-9]+$")) brojUlice++;
            }
            if (brojUlice == 1 && brojReci + brojUlice == niz.Length) return true;
            return false;
        }
        private bool ProveraMaticni(string maticni)
        {

            if ((maticni.Length == 8 || maticni.Length == 9) && Regex.IsMatch(maticni, @"^[0-9]+$")
                && !maticni.StartsWith("0") && !maticni.Equals("10000000")) return true;
            return false;
        }
        private bool ProveraDelatnost(string ime)
        {
            if (!(ime is null) && (ime.Length >= 2 && Regex.IsMatch(ime, @"^[a-z A-Z]+$"))) return true;
            return false;
        }
    }
}

ZaposleniMVC/Controllers/RasporedController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ZaposleniMVC.Models;

namespace ZaposleniMVC.Controllers
{
    public class RasporedController : Controller
    {
        private readonly ApplicationDbContext _db;


        public RasporedController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var zaposleni = _db.Zaposleni.ToList();

            var rasp = _db.Raspored.Include((r) => r.Zaposleni).OrderByDescending((r)=> r.Datum);
             ;


            Odgovor o = new Odgovor()
            {
                Zaposleni = zaposleni,
                Rasporedi = rasp.ToList()
            };
            return View(o);
        }

        public IActionResult Create()
        {
            var zaposleni = _db.Zaposleni.ToList();
            Odgovor o = new Odgovor()
            {
                Zaposleni = zaposleni,
                Ras = new Raspored()
            };
            return View(o);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm]DateTime datum,[FromForm] string smena,[FromForm] string zaposlen,[FromForm]string obavestenje)
        {
            Odgovor o = new Odgovor();
            o.Zaposleni = _db.Zaposleni.ToList();
            o.Ras = new Raspored();
            if (!(_db.Raspored.SingleOrDefault((r) => r.Datum == datum && (r.Zaposleni.Ime + r.Zaposleni.Prezime).Equals(zaposlen)) is null))
            {
                o.Poruka = "Ima";
                return View(o);
            }
            try
            {
                _db.Add(KreirajRaspored(datum, smena, zaposlen, obavestenje));
                _db.SaveChanges();
                
                o.Poruka = "Uspesno";
            }
            catch (Exception)
            {
                o.Poruka = "Ne";
                throw;
                
            }
            return View(o);
        }

       

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Search(string zaposlen)
        {
            Odgovor o = new Odgovor();
            o.Zaposleni = _db.Zaposleni.ToList();
            var rasporedi = _db.Raspored.Where((r) => (r.Zaposleni.Ime+r.Zaposleni.Prezime).Equals(zaposlen));
           
            if ((rasporedi is null) || rasporedi.Count() == 0 )
            {
                o.Rasporedi = _db.Raspored.ToList();
                
                o.Poruka = "Nema";
                return View(o);
            }
            o.Poruka = "Ima";
            o.Rasporedi = rasporedi.OrderByDescending(r => r.Datum).ToList() ;
            return View(o);
        }

        private Raspored KreirajRaspored(DateTime datum, string smena, string zaposlen, string obavestenje)
        {
            Raspored r = new Raspored();
            r.Datum = datum;
            r.Smena = smena;

            r.Zaposleni = _db.Zaposleni.Single((z) => (z.Ime + z.Prezime).Equals(zaposlen));
            r.Administrator = _db.Administratori.Single((a) => a.AdministratorID == 5);
            r.Obavestenje = obavestenje;
            r.Kasni = false;
            r.VremePrijave = new DateTime(1389,06,28);
            return r;
        }

        public IActionResult Edit(string datum,string zaposleni)
        {
            DateTime dat = Convert.ToDateTime(datum);
            var zaposlen = _db.Zaposleni.ToList();
            var raspo = _db.Raspored.Single((r) => r.Datum.Date == dat.Date && (r.Zaposleni.Ime + r.Zaposleni.Prezime).Equals(zaposleni));
            Odgovor o = new Odgovor()
            {
                Zaposleni = zaposlen,
                Ras = raspo
            };
            return View(o);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromForm]Raspored ras)
        {
            ras.Administrator = _db.Administratori.Single((a) => a.AdministratorID == 5);
            var r = _db.Raspored.Single((ra) => ra.RasporedID == ras.RasporedID);
            r.Smena = ras.Smena;
            r.Obavestenje = ras.Obavestenje;
            try
            {
                _db.Update(r);
                _db.SaveChanges();
            }
            catch (Exception)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

       
        
        public IActionResult Delete(string datum, string zaposleni)
        {
            DateTime dat = Convert.ToDateTime(datum);
            var zaposlen = _db.Zaposleni.ToList();
            var raspo = _db.Raspored.Single((r) => r.Datum.Date == dat.Date && (r.Zaposleni.Ime + r.Zaposleni.Prezime).Equals(zaposleni));
            _db.Entry(raspo).State = EntityState.Deleted;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ZaposleniMVC/Controllers/VisualizeDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ZaposleniMVC.Models;

namespace ZaposleniMVC.Controllers
{
    public class VisualizeDataController : Controller
    {
        private readonly ApplicationDbContext _db;


        public VisualizeDataController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult ColumnChart()
        {
            return View();
        }
        public ActionResult PodaciZaposleni()
        {
            return Json(Rezultati("Prva"));
        }
        public List<Obavestenja> Rezultati(string smena)
        {
            List<Obavestenja> obav = new List<Obavestenja>();
            var zaposleni = _db.Zaposleni;
            foreach(var i in zaposleni)
            {
                int brojac = 0;
                var rasporedi = _db.Raspored.Where((r) => r.Zaposleni.OsobaID == i.OsobaID).ToList();
                rasporedi.ForEach((r) =>
                {
                    if (r.Smena == smena) brojac++;

                });
                Obavestenja o = new Obavestenja();
                o.ImePrezime = i.Ime + " " + i.Prezime;
                o.Smena = "Prva";
                o.BrojSmena = brojac;
                obav.Add(o);
            }
            return obav;
        }
        public ActionResult PodaciZaposleni2()
        {
            return Json(Rezultati("Druga"));
        }
        public ActionResult PodaciZaposleni3()
        {
            return Json(Rezultati("Ne radi"));
        }
    }
}

ZaposleniMVC/Views/Raspored/Create.cshtml
@model ZaposleniMVC.Models.Odgovor
@{
    ViewData["Title"] = "Create";
}

<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator">Zaposleni</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Raspored" asp-action="Index">Raspored</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Kompanija" asp-action="Index">Kompanija</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>



<form asp-controller="Raspored" asp-action="Create" method="post" style="margin-top: 50px">
    <div class="container">


        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Ras.Datum"></label>
                </div>
                <div class="col-sm-4">
                    <input type="date" name="Datum" class="form-control" />
                </div>

            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Ras.Smena"></label>
                </div>
                <div class="col-sm-4">
                    <select name="Smena" class="form-control">
                        <option value="Prva">Prva</option>
                        <option value="Druga">Druga</option>
                        <option value="NeRadi">Ne radi</option>
                    </select>

                </div>

            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Ras.Zaposleni"></label>
                </div>
                <div class="col-sm-4">
                    <select name="Zaposlen" class="form-control">

                        @foreach (var i in Model.Zaposleni)
                        {
                            <option value="@i.Ime@i.Prezime">@Html.DisplayFor(m => i.Ime) @Html.DisplayFor(m => i.Prezime)</option>
                        }

                    </select>

                </div>

            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Ras.Obavestenje"></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" name="Obavestenje" class="form-control" />

                </div>

            </div>
        </div>

        <br />
        <div class="form-group">
            <input type="submit" value="Kreiraj" class="btn btn-sm btn-primary" />
            <a asp-action="Index" class="btn btn-sm btn-primary">Vrati nazad</a>
            <h6 id="poruka"></h6>



            <br />

        </div>
    </div>

</form>

@if (!(Model.Poruka is null) && Model.Poruka != "")
{
    if (Model.Poruka == "Uspesno")
    {
        <script>
            document.getElementById('poruka').innerText = "Uspesno ste kreirali raspored!";
            document.getElementById('poruka').style.color = 'green';
        </script>
    }
    else if (Model.Poruka == "Ne")
    {
        <script>
            document.getElementById('poruka').innerText = "Sistem ne moze da kreira raspored!";
            document.getElementById('poruka').style.color = 'red';
        </script>
    }
    else
    {
        <script>
            document.getElementById('poruka').innerText = "Postoji vec kreiran raspored!";
            document.getElementById('poruka').style.color = 'red';
        </script>
    }
}

ZaposleniMVC/Views/Raspored/Edit.cshtml
@model ZaposleniMVC.Models.Odgovor
@{
    ViewData["Title"] = "Edit";
}


<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator">Zaposleni</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Raspored" asp-action="Index">Raspored</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Kompanija" asp-action="Index">Kompanija</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>



<form asp-controller="Raspored" asp-action="Edit" method="post" style="margin-top: 50px">
    <div class="container">

        <input asp-for="Ras.Administrator" hidden />
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Ras.Datum"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Ras.Datum" class="form-control" readonly />
                    <input asp-for="Ras.RasporedID" hidden />
                </div>

            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Ras.Smena"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Ras.Smena" class="form-control" />
                </div>

            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Ras.Obavestenje"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Ras.Obavestenje" class="form-control" />

                </div>

            </div>
        </div>

        <br />
        <div class="form-group">
            <input type="submit" value="Izmeni" class="btn btn-sm btn-primary" />
            <a asp-action="Index" class="btn btn-sm btn-primary">Vrati nazad</a>
            <h6 id="poruka"></h6>



            <br />

        </div>
    </div>

</form>

@if (!(Model.Poruka is null) && Model.Poruka != "")
{
    if (Model.Poruka == "Uspesno")
    {
        <script>
            document.getElementById('poruka').innerText = "Uspesno ste kreirali raspored!";
            document.getElementById('poruka').style.color = 'green';
        </script>
    }
    else if (Model.Poruka == "Ne")
    {
        <script>
            document.getElementById('poruka').innerText = "Sistem ne moze da kreira raspored!";
            document.getElementById('poruka').style.color = 'red';
        </script>
    }
    else
    {
        <script>
            document.getElementById('poruka').innerText = "Postoji vec kreiran raspored!";
            document.getElementById('poruka').style.color = 'red';
        </script>
    }
}

ZaposleniMVC/Views/Raspored/Index.cshtml
@model ZaposleniMVC.Models.Odgovor



<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator">Zaposleni</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Raspored" asp-action="Index">Raspored</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Kompanija" asp-action="Index">Kompanija</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>



<h3>Zaposleni: </h3>
<hr />
<form asp-controller="Raspored" asp-action="Search">
    <div class="container">
        <p>
            <br />
            <select name="Zaposlen" style="border-color:blue">

                @foreach (var i in Model.Zaposleni)
                {
                    <option value="@i.Ime@i.Prezime">@Html.DisplayFor(m => i.Ime) @Html.DisplayFor(m => i.Prezime)</option>
                }

            </select>
            <input id="btnSearch" type="submit" value="Sortiraj" class="btn btn-sm btn-success" style="position:absolute; left:310px " />
            <a asp-controller="VisualizeData" asp-action="ColumnChart" class="btn btn-sm btn-primary" style="position:absolute; left:380px">Statistika</a>
        </p>

    </div>
</form>


@if (!(Model.Rasporedi is null) && Model.Rasporedi.Count() > 0)
{
    <div class="table-bordered">
        <table class="table">
            <tr>
                @{
                    var parms = 0;
                }
                <th>Datum</th>
                <th>Smena</th>
                <th>Obavestenja</th>
                <th>Zaposleni</th>
                <th>Vreme prijave</th>
                <th>Prijavljen</th>
                @foreach (var i in Model.Rasporedi)
                {
                <tr>
                    <td>
                        <h5>@Html.Encode(i.Datum.ToString("dd-MM-yyyy"))</h5>
                    </td>
                    <td>
                        @Html.DisplayFor(m => i.Smena)
                        @if (i.Smena == "")
                        {
                            parms += 1;
                        }

                    </td>
                    <td>
                        @Html.DisplayFor(m => i.Obavestenje)
                    </td>
                    <td>
                        @Html.DisplayFor(m => i.Zaposleni.Ime) @Html.DisplayFor(m => i.Zaposleni.Prezime)
                    </td>
                    <td>

                        @if (i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28)
                        {
                            @Html.Encode("");
                        }
                        else
                        {
                            @Html.Encode(i.VremePrijave.ToString("HH:mm tt"));

                        }
                    </td>
                    <td>
                        @if (i.Datum.Date <= DateTime.Now.Date)
                        {
                            if (i.Kasni == false && (i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                            {
                                <h5><b>@Html.Encode("Nije prijavljen")</b></h5>
                            }
                            else if (i.Kasni == false && !(i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                            {
                                <h5 style="color:forestgreen"><b>@Html.Encode("Na vreme")</b></h5>

                            }
                            else
                            {
                                <h5 style="color:red"><b>@Html.Encode("Kasni")</b></h5>
                            }
                        }
                        else
                        {
                            <h5 style="color:blue"><b>Datum!</b> </h5>
                        }


                    </td>
                    <td>
                        @{
                            var Parms = new Dictionary<string, string>
                                                                {
                                                                        { "datum",i.Datum.ToString() },
                                                                            {"zaposleni",(i.Zaposleni.Ime + i.Zaposleni.Prezime) }
                                                                };
                        }


                        @if (i.Datum.Date < DateTime.Now.Date)
                        {
                            <a asp-action="Delete" asp-controller="Raspored" asp-all-route-data="Parms" class="btn btn-sm btn-danger">Obrisi</a>
                        }
                        else
                        {
                            <a asp-action="Edit" asp-controller="Raspored" asp-all-route-data="Parms" class="btn btn-sm btn-default">Izmeni</a>

                            <a asp-action="Delete" asp-controller="Raspored" asp-all-route-data="Parms" class="btn btn-sm btn-danger">Obrisi</a>

                        }
                    </td>
                </tr>
            }


            </table>

        </div>
        @if (parms > 0)
        {
            <div class="container">
                <p>
                    <h5 style="color:red">@Html.Encode("Imate " + parms + " zahteva za kreiranjem rasporeda")</h5>
                </p>
            </div>
        }
        
    }
    else
    {
        <h3>Nema rasporeda jos</h3>
    }
<div class="container">
    <p>
        <br />
        <a asp-action="Create" asp-controller="Raspored" class="btn btn-sm btn-primary"> Kreiraj zaposlenog</a>
        <a asp-action="Index" asp-controller="Raspored" class="btn btn-sm btn-success" style="position:absolute; right:150px"> Resetuj</a>

    </p>

</div>

ZaposleniMVC/Views/Raspored/Search.cshtml
@model ZaposleniMVC.Models.Odgovor



<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator">Zaposleni</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Raspored" asp-action="Index">Raspored</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Kompanija" asp-action="Index">Kompanija</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>



<h3>Zaposleni: </h3>
<hr />
<form asp-controller="Raspored" asp-action="Search">
    <div class="container">
        <p>
            <br />
            <select name="Zaposlen" style="border-color:blue">

                @foreach (var i in Model.Zaposleni)
                {
                    <option value="@i.Ime@i.Prezime">@Html.DisplayFor(m => i.Ime) @Html.DisplayFor(m => i.Prezime)</option>
                }

            </select>
            <input id="btnSearch" type="submit" value="Sortiraj" class="btn btn-sm btn-default" style="position:absolute; left:310px " />

            <h6 id="poruka"></h6>
        </p>

    </div>
</form>

@if (!(Model.Rasporedi is null) && Model.Rasporedi.Count() > 0)
{
    <div class="table-bordered">
        <table class="table">
            <tr>

                <th>Datum</th>
                <th>Smena</th>
                <th>Obavestenja</th>
                <th>Zaposleni</th>
                <th>Prijavljen</th>
                @foreach (var i in Model.Rasporedi)
                {
                <tr>
                    <td>
                        @Html.Encode(i.Datum.ToString("dd-MM-yyyy"))
                    </td>
                    <td>
                        @Html.DisplayFor(m => i.Smena)
                    </td>
                    <td>
                        @Html.DisplayFor(m => i.Obavestenje)
                    </td>
                    <td>
                        @Html.DisplayFor(m => i.Zaposleni.Ime) @Html.DisplayFor(m => i.Zaposleni.Prezime)
                    </td>
                    <td>
                        @if (i.Kasni == false && (i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                        {
                            @Html.Encode("Nije prijavljen");
                        }
                        else if (i.Kasni == false && !(i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                        {
                            @Html.Encode("Kasni");
                        }
                        else
                        {
                            @Html.Encode("Na vreme");
                        }
                    </td>
                    <td>

                        @{
                            var Parms = new Dictionary<string, string>
                                                {
                                                        { "datum",i.Datum.ToString() },
                                                            {"zaposleni",(i.Zaposleni.Ime + i.Zaposleni.Prezime) }
                                                };
                        }


                        <a asp-action="Edit" asp-controller="Raspored" asp-all-route-data="Parms" class="btn btn-sm btn-default">Izmeni</a>

                        <a asp-action="Delete" asp-controller="Raspored" asp-all-route-data="Parms" class="btn btn-sm btn-danger">Obrisi</a>


                    </td>
                </tr>
            }


            </table>

        </div>
    }
    else
    {
        <h3>Nema rasporeda jos</h3>
    }
<div class="container">
    <p>
        <br />
        <a asp-action="Create" asp-controller="Raspored" class="btn btn-sm btn-primary"> Kreiraj zaposlenog</a>
        <a asp-action="Index" asp-controller="Raspored" class="btn btn-sm btn-success" style="position:absolute; right:150px"> Resetuj</a>
    </p>

</div>

@if (!(Model.Poruka is null) && Model.Poruka != "")
{
    if (Model.Poruka == "Nema")
    {
        <script>
            document.getElementById('poruka').innerText = "Ne postoji raspored za datog zaposlenog";
            document.getElementById('poruka').style.color = 'red';
        </script>
    }

}