ZaposleniMVC/Controllers/KompanijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ZaposleniMVC.Models;

namespace ZaposleniMVC.Controllers
{
    public class KompanijaController : Controller
    {
        private readonly ApplicationDbContext _db;


        public KompanijaController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            Odgovor o = new Odgovor();
            if (_db.Kompanija.Count() == 0)
            {
                o.Kompanija = new Kompanija();

                return View(o);
            }

            return RedirectToAction("Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Kompanija kompanija)
        {
            Odgovor o = new Odgovor();
            o.Kompanija = new Kompanija();
            try
            {
                _db.Add(kompanija);
                _db.SaveChanges();
                return RedirectToAction("Edit");

            }
            catch (Exception)
            {

                o.Poruka = "Greska";
            }
            return View(o);
        }

        public IActionResult Edit()
        {
            Odgovor o = new Odgovor();
            o.Kompanija = _db.Kompanija.First();

            return View(o);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Kompanija kompanija)
        {
            Odgovor o = new Odgovor();
            o.Kompanija = kompanija;

            try
            {
                List<string> lista = ProveraOpste(o.Kompanija);
                if (lista.Count > 0)
                {
                    o.Validacija = lista;
                    o.Poruka = "Greska";
                    return View(o);
                }
                _db.Update(kompanija);
                _db.SaveChanges();
                o.Poruka = "Ok";

            }
            catch (Exception)
            {

                o.Poruka = "Greska";
            }
            return View(o);
        }

        private List<string> ProveraOpste(Kompanija kompanija)
        {
            List<string> lista = new List<string>();
            if (!ProveraNaziv(kompanija.Naziv)) lista.Add("naziv");
            if (!ProveraMaticni(kompanija.MaticniBroj)) lista.Add("maticni");
            if (!ProveraDelatnost(kompanija.Delatnost)) lista.Add("delatnost");
            if (!ProveraAdresa(kompanija.Adresa)) lista.Add("adresa");


            return lista;

        }

        private bool ProveraNaziv(string naziv)
        {
            if (naziv is null || naziv.Length <= 2) return false;
            return true;
        }
        private bool ProveraAdresa(string adresa)
        {
            if (adresa is null) return false;
            string[] niz = adresa.Split(' ');
            int brojReci = 0;
            int brojUlice = 0;
            foreach (string s in niz)
            {
                if (Regex.IsMatch(s, @"^[a-zA-Z]+$")) brojReci++;
                if (Regex.IsMatch(s, @"^[0-9]+$")) brojUlice++;
            }
            if (brojUlice == 1 && brojReci + brojUlice == niz.Length) return true;
            return false;
        }
        private bool ProveraMaticni(string maticni)
        {

            if ((maticni.Length == 8 || maticni.Length == 9) && Regex.IsMatch(maticni, @"^[0-9]+$")
                && !maticni.StartsWith("0") && !maticni.Equals("10000000")) return true;
            return false;
        }
        private bool ProveraDelatnost(string ime)
        {
            if (!(ime is null) && (ime.Length >= 2 && Regex.IsMatch(ime, @"^[a-z A-Z]+$"))) return true;
            return false;
        }
    }
}

ZaposleniMVC/Controllers/RadnikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ZaposleniMVC.Models;
using ZaposleniMVC.ModelsFunction;

namespace ZaposleniMVC.Controllers
{
    public class RadnikController : Controller
    {
        private readonly ApplicationDbContext _db;


        public RadnikController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
           Odgovor o = new Odgovor();
            if(Sesija.Instance.Zaposlen is null)
            {
                return NotFound();
            }
            var zaposlen = Sesija.Instance.Zaposlen.Ime+Sesija.Instance.Zaposlen.Prezime;
            
            var rasporedi = _db.Raspored.Include((r) => r.Zaposleni);
            var listaRasporeda = rasporedi.Where((r) => (r.Zaposleni.Ime + r.Zaposleni.Prezime).Equals(zaposlen)).ToList();
            if (listaRasporeda.Count() == 0)
            {
                
            }
           
            listaRasporeda.OrderByDescending((r) => r.Datum);
            o.Rasporedi = listaRasporeda;
            o.Zap = Sesija.Instance.Zaposlen;
            
            return View(o);
        }

        public IActionResult Prijava(string datum, string zaposleni)
        {
            DateTime dat = Convert.ToDateTime(datum);
            var zaposlen = _db.Zaposleni.ToList();
            var raspo = _db.Raspored.Single((r) => r.Datum == dat && (r.Zaposleni.Ime + r.Zaposleni.Prezime).Equals(zaposleni));
            raspo.VremePrijave = DateTime.Now;
            if (ProveraKasni(raspo) == false) raspo.Kasni = true;
            _db.Update(raspo);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Search([FromForm]DateTime datum)
        {
            Odgovor o = new Odgovor();
            var raspored = _db.Raspored.Include((r)=> r.Zaposleni).Where((r) => r.Datum.Date == datum && r.Zaposleni.OsobaID == Sesija.Instance.Zaposlen.OsobaID);
            
            if (raspored.Count()==0)
            {
                return RedirectToAction("Index");
            }
            o.Rasporedi = raspored.ToList();
            return View(o);
        }

        [HttpGet]
        public async Task< IActionResult> Create(Raspored r)
        {
           
            r.Datum = DateTime.Now;
            r.VremePrijave = DateTime.Now;
            r.Zaposleni = _db.Zaposleni.Single((z) => z.OsobaID == Sesija.Instance.Zaposlen.OsobaID);
            r.Administrator = _db.Administratori.Single((a) => a.AdministratorID == 5);
            r.Smena = "";
            r.Obavestenje = "";
            
            r.Kasni = false;
            _db.Add(r);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
            

        }

        [HttpPost]
        public IActionResult Vrati(string datum)
        {
            DateTime da = Convert.ToDateTime(datum);
            var raspored = _db.Raspored.Include((r) => r.Zaposleni).Where((r) => r.Datum.Date == da && r.Zaposleni.OsobaID == Sesija.Instance.Zaposlen.OsobaID);
            Odgovor o = new Odgovor();
            o.Rasporedi = raspored.ToList();
            
            return PartialView("Vrati",o);
        }

        private bool ProveraKasni(Raspored r)
        {
            if(r.Smena == "Prva")


            {
                if(r.VremePrijave.Hour <= 8)
                {
                    return true;
                }
            }
            else
            {
                if (r.VremePrijave.Hour <= 15) return true;
            }
            return false;
        }

        private Raspored KreirajRaspored()
        {
            Raspored r = new Raspored();
            r.Datum = new DateTime(DateTime.Now.Year,DateTime.Now.Month,DateTime.Now.Day);
            
            r.Smena = "";

            r.Zaposleni = Sesija.Instance.Zaposlen;
            r.Administrator = _db.Administratori.Single((a) => a.AdministratorID == 5);
            r.Obavestenje = "";
            r.Kasni = false;
            r.VremePrijave = new DateTime(1389, 06, 28);
            return r;

        }

        public IActionResult Profil()
        {
            var zaposlen = Sesija.Instance.Zaposlen;
            zaposlen = _db.Zaposleni.Single((z) => z.OsobaID == zaposlen.OsobaID);
            Odgovor o = new Odgovor();
            o.Zap = zaposlen;
            return View(o);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Profil([FromForm]Odgovor z)
        {
            
            
            try
            {
               

                _db.Update(z.Zap);
                _db.SaveChanges();
                
                z.Poruka = "Ok";
            }
            catch (Exception)
            {

                z.Poruka = "Greska";
            }
            return View(z);
            
        }
    }
}

ZaposleniMVC/Views/Radnik/Index.cshtml
@model ZaposleniMVC.Models.Odgovor


<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Radnik" asp-action="Index">Raspored</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Radnik" asp-action="Profil">Profil</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Kompanija" asp-action="Obavestenja">Obavestenja</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Zaposleni" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<h3>Raspored: @Model.Zap.Ime @Model.Zap.Prezime </h3>
<hr />


    <div class="container">
        <p>
            <br />
            <input type="date" id="datum" name="datum" />
            <input id="btnPretrazi" type="submit" value="Pretrazi" class="btn btn-sm btn-success" style="position:absolute; left:310px " />
            <a asp-action="Index" class="btn btn-sm btn-default" style="position:absolute; left:380px">Resetuj</a>

        </p>

    </div>
    
        @if (!(Model.Rasporedi is null) && Model.Rasporedi.Count() > 0)
        {<div id="ubaci">
             <div class="table-bordered">
                 <table class="table">
                     <tr>

                         <th>Datum</th>
                         <th>Smena</th>
                         <th>Radno vreme</th>
                         <th>Obavestenja</th>
                         <th>Prijava</th>
                         @{
                             var parms = 0;
                         }
                         @foreach (var i in Model.Rasporedi)
                         {
                         <tr id="provera">
                             <td>
                                 @Html.Encode(i.Datum.ToString("dd-MM-yyyy"))
                             </td>
                             <td>
                                 @Html.DisplayFor(m => i.Smena)
                             </td>
                             <td>

                                 @{
                                     var par = "";
                                     if (i.Smena == "Prva")
                                     {
                                         par = "8-15h";
                                     }
                                     else if (i.Smena == "Druga")
                                     {
                                         par = "15-22h";
                                     }
                                     else if (i.Smena == "Ne radi")
                                     {
                                         par = "Slobodan dan";
                                     }
                                     else
                                     {
                                         par = "";
                                     }
                                 }
                                 @Html.Encode(par + "")
                             </td>
                             <td>
                                 @Html.DisplayFor(m => i.Obavestenje)
                             </td>

                             <td>

                                 @{
                                     var Parms = new Dictionary<string, string>
                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                            { "datum",i.Datum.ToString() },
                                                                                                                                                                                                                                                                                {"zaposleni",(i.Zaposleni.Ime + i.Zaposleni.Prezime) }
                                                                                                                                                                                                                                                                    };
                                 }
                                 @if (i.Smena != "")
                                 {
                                     @if ((i.Datum.Year == DateTime.Now.Year && i.Datum.Month == DateTime.Now.Month
                                                                  && i.Datum.Day == DateTime.Now.Day))
                                     {
                                         parms += 1;
                                         if (i.Kasni == false && (i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                                         {
                                             <a asp-action="Prijava" asp-controller="Radnik" asp-all-route-data="Parms" class="btn btn-sm btn-success">Prijava</a>
                                         }
                                         else if (i.Kasni == false && !(i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                                         {
                                             <h5 style="color:green"><b>@Html.Encode("Prijavljen")</b></h5>
                                         }
                                         else
                                         {
                                             <h5 style="color:red"><b>@Html.Encode("Kasni")</b></h5>
                                         }



                                     }
                                     else
                                     {
                                         if (i.Kasni == false && !(i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                                         {
                                             <h5 style="color:green"><b>@Html.Encode("Prijavljen")</b></h5>
                                         }
                                         else if (i.Kasni == true && !(i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                                         {
                                             <h5 style="color:red"><b>@Html.Encode("Kasni")</b></h5>
                                         }
                                         else
                                         {
                                             <h5 style="color:blue"><b>@Html.Encode("Datum/Nije prijavljen")</b></h5>
                                         }

                                     }

                                 }
                                 else
                                 {
                                     parms += 1;
                                     <input type="button" id="posaljiMail" value="Posalji mail" onclick="posaljiMail('@Model.Zap.Ime','@Model.Zap.Prezime','@DateTime.Now')" class="btn btn-sm btn-default" />
                                     <h5 style="color:green"><b>@Html.Encode("Vreme evidentirano")</b></h5>

                                 }
                             </td>
                         </tr>


                                     }
                     </table>

                 </div>
        </div>

        @if (parms == 0)
        {
            <div class="container">
                <p>
                    <h5>Raspored za danasnji dan nije kreiran: </h5>
                    <a asp-action="Create" class="btn btn-sm btn-default">Kreiraj</a>
                </p>
            </div>
        }
                                     }

        <script>
            function posaljiMail(ime,prezime,datum) {
                var data = {
                    service_id: 'gmail',
                    template_id: 'template_d6XiZz5A',
                    user_id: 'user_lcrECp1s9bUxbmrahpjSE',
                    template_params: {
                        'from_name': ime + ' ' + prezime,
                        'message_html': 'Saljem vam mail posto mi nije kreiran raspored za '+datum,
                        'to_name': 'Nikola'
                    }
                };
                
                $.ajax('https://api.emailjs.com/api/v1.0/email/send', {
                    type: 'POST',
                    data: JSON.stringify(data),
                    contentType: 'application/json'
                }).done(function () {
                    document.getElementById('posaljiMail').style.borderColor = 'green';
                    document.getElementById('posaljiMail').style.borderWidth = '1px';
                    
                    }).fail(function (error) {
                        document.getElementById('posaljiMail').style.background = 'red';
                        document.getElementById('posaljiMail').style.borderWidth = '1px';
                    
                });
            }

        </script>

ZaposleniMVC/Views/Radnik/Profil.cshtml
@model ZaposleniMVC.Models.Odgovor



    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator" class="navbar-brand"></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a asp-area="" asp-controller="Radnik" asp-action="Index">Raspored</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Radnik" asp-action="Profil">Profil</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Kompanija" asp-action="Obavestenja">Obavestenja</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Zaposleni" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <form asp-action="Profil" method="post" style="margin-top: 50px">
        <div class="container">


            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Zap.Ime"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Zap.Ime" class="form-control" />
                        <input asp-for="Zap.OsobaID" hidden />
                    </div>

                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Zap.Prezime"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Zap.Prezime" class="form-control" />
                    </div>

                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Zap.Adresa"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Zap.Adresa" class="form-control" />

                    </div>

                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Zap.BrojTelefona">Broj telefona</label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Zap.BrojTelefona" class="form-control" />

                    </div>

                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Zap.Email"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Zap.Email" class="form-control" />

                    </div>

                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Zap.Sifra"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Zap.Sifra" class="form-control" />

                    </div>

                </div>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Izmeni" class="btn  btn-primary" />
                @if(Model.Poruka == "Ok")
                {
                    <h6>Uspesna izmena!</h6>
                }else if (Model.Poruka == "Greska")
                {
                    <h6>Greska</h6>
                }

                <br />

            </div>
        </div>

    </form>

ZaposleniMVC/Views/Radnik/Search.cshtml
@model ZaposleniMVC.Models.Odgovor


    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Zaposleni" asp-action="IndexAdministrator" class="navbar-brand"></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a asp-area="" asp-controller="Radnik" asp-action="Index">Raspored</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Radnik" asp-action="Profil">Profil</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Kompanija" asp-action="Obavestenja">Obavestenja</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Zaposleni" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <h3>Raspored: @Model.Rasporedi[0].Zaposleni.Ime @Model.Rasporedi[0].Zaposleni.Prezime </h3>
    <hr />

    <form asp-controller="Radnik" asp-action="Search">
        <div class="container">
            <p>
                <br />
                <input type="date" name="datum" />
                <input id="btnSearch" type="submit" value="Pretrazi" class="btn btn-sm btn-success" style="position:absolute; left:310px " />
                <a asp-action="Index" class="btn btn-sm btn-default" style="position:absolute; left:380px">Resetuj</a>
            </p>

        </div>
    </form>

    @if (!(Model.Rasporedi is null) && Model.Rasporedi.Count() > 0)
    {
        <div class="table-bordered">
            <table class="table">
                <tr>

                    <th>Datum</th>
                    <th>Smena</th>
                    <th>Radno vreme</th>
                    <th>Obavestenja</th>
                    <th>Prijava</th>
                    @foreach (var i in Model.Rasporedi)
                    {
                    <tr id="provera">
                        <td>
                            @Html.Encode(i.Datum.ToString("dd-MM-yyyy"))
                        </td>
                        <td>
                            @Html.DisplayFor(m => i.Smena)
                        </td>
                        <td>

                            @{
                                var par = "";
                                if (i.Smena == "Prva")
                                {
                                    par = "8-15h";
                                }
                                else if (i.Smena == "Druga")
                                {
                                    par = "15-22h";
                                }
                                else
                                {
                                    par = "Slobodan dan";
                                }
                            }
                            @Html.Encode(par + "")
                        </td>
                        <td>
                            @Html.DisplayFor(m => i.Obavestenje)
                        </td>

                        <td>

                            @{
                                var Parms = new Dictionary<string, string>
                                                                                                                    {
                                                                                                                            { "datum",i.Datum.ToString() },
                                                                                                                                {"zaposleni",(i.Zaposleni.Ime + i.Zaposleni.Prezime) }
                                                                                                                    };
                            }

                            @if ((i.Datum.Year == DateTime.Now.Year && i.Datum.Month == DateTime.Now.Month
                        && i.Datum.Day == DateTime.Now.Day))
                            {
                                if (i.Kasni == false && (i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                                {
                                    <a asp-action="Prijava" asp-controller="Radnik" asp-all-route-data="Parms" class="btn btn-sm btn-success">Prijava</a>
                                }
                                else if (i.Kasni == false && !(i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                                {
                                    <h5 style="color:green"><b>@Html.Encode("Prijavljen")</b></h5>
                                }
                                else
                                {
                                    <h5 style="color:red"><b>@Html.Encode("Kasni")</b></h5>
                                }



                            }
                            else
                            {
                                if (i.Kasni == false && !(i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                                {
                                    <h5 style="color:green"><b>@Html.Encode("Prijavljen")</b></h5>
                                }
                                else if (i.Kasni == true && !(i.VremePrijave.Year == 1389 && i.VremePrijave.Month == 06 && i.VremePrijave.Day == 28))
                                {
                                    <h5 style="color:red"><b>@Html.Encode("Kasni")</b></h5>
                                }
                                else
                                {
                                    <h5 style="color:blue"><b>@Html.Encode("Datum/Nije prijavljen")</b></h5>
                                }

                            }
                        </td>
                    </tr>

                }
                </table>

            </div>
        }
        else
        {
            <h3>Nema rasporeda jos</h3>
        }

   